### ISSUE TITLE
Dunnos still broken

### ISSUE THREAD

**Issue by Kexus** [Azimath/discordbot#2]
Fix when?

**Comment by Yergermeister** [comment]
༼つ ◕_◕ ༽つ༼つ ◕_◕ ༽つ༼つ ◕_◕ ༽つ gib fix ༼つ ◕_◕ ༽つ༼つ ◕_◕ ༽つ༼つ ◕_◕ ༽つ

**Comment by Azimath** [comment]
Fixed by commit ce0761324889d3a0f6d8c72be97ddf575cdac436
